apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-website-ingress
  namespace: "2401014"
  labels:
    app: movie-website
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: movie-website-2401014.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-website
                port:
                  number: 80
