apiVersion: v1
kind: Service
metadata:
  name: movie-website
  namespace: default
  labels:
    app: movie-website
    service: movie-website
spec:
  type: NodePort
  selector:
    app: movie-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  sessionAffinity: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-website-ingress
  namespace: default
  labels:
    app: movie-website
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: movie-website.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: movie-website
                port:
                  number: 80
