apiVersion: v1
kind: Service
metadata:
  name: movie-website
  namespace: "2401014"
  labels:
    app: movie-website
    service: movie-website
spec:
  type: NodePort
  selector:
    app: movie-website
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  sessionAffinity: None
